// This is an autogenerated file from Firebase Studio.
'use client';

import { useState, useEffect } from 'react';
import { AuthForm } from '@/components/auth/auth-form';
import { useAuth } from '@/hooks/useAuth';
import { useRouter } from 'next/navigation';
import { useToast } from "@/hooks/use-toast";
import { Loader2 } from 'lucide-react';

export default function LoginPage() {
  const { login, user, isLoading: authLoading } = useAuth();
  const router = useRouter();
  const { toast } = useToast();
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    if (user && !authLoading) {
      // Admin always goes to /admin. Non-admin users (if any existed) would go to /plans.
      router.push(user.isAdmin ? '/admin' : '/admin'); 
    }
  }, [user, authLoading, router]);

  const handleLogin = async (email: string, password_DoNotStore: string) => {
    setErrorMessage(null);
    const success = await login(email, password_DoNotStore);
    if (success) {
      toast({
        title: "Login Successful",
        description: "Welcome back to Finance Flow Admin Panel!",
      });
      // Effect hook will handle redirection
    } else {
      setErrorMessage("Invalid email or password. Please try again.");
      toast({
        title: "Login Failed",
        description: "Invalid email or password. Please try again.",
        variant: "destructive",
      });
    }
  };
  
  if (authLoading || user) {
    return (
      <div className="flex justify-center items-center min-h-screen bg-slate-900 text-white">
        <Loader2 className="h-8 w-8 animate-spin" />
        <p className="ml-2">Loading...</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col justify-center items-center min-h-screen bg-slate-900 dark py-12 px-4">
      <AuthForm mode="login" onSubmit={handleLogin} errorMessage={errorMessage} />
    </div>
  );
}
